# Generated by Django 4.2.14 on 2025-09-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.CharField(
                blank=True,
                help_text="Ej: Programación, Música, Deportes...",
                max_length=255,
                null=True,
                verbose_name="Intereses",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Ciudad o país donde te encuentras.",
                max_length=100,
                null=True,
                verbose_name="Ubicación",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Tu nombre real o el que quieras mostrar públicamente.",
                max_length=100,
                null=True,
                verbose_name="Nombre completo",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Número de contacto (opcional).",
                max_length=20,
                null=True,
                verbose_name="Teléfono",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Biografía"),
        ),
    ]
