# Generated by Django 4.2.14 on 2025-09-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_reviewvote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("visible", "Visible"),
                    ("hidden", "Oculto"),
                    ("blocked", "Bloqueado"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
