# Generated by Django 4.2.14 on 2025-09-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_comment_is_approved_comment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("visible", "Visible"),
                    ("hidden", "Oculto"),
                    ("blocked", "Bloqueado"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
