# Generated by Django 4.2.14 on 2025-09-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_postblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="platform",
            field=models.CharField(
                choices=[
                    ("pc", "PC"),
                    ("xbox", "Xbox"),
                    ("nintendo", "Nintendo Switch"),
                    ("mobile", "Celular"),
                ],
                default="pc",
                max_length=20,
            ),
        ),
    ]
