# Generated by Django 4.2.14 on 2025-09-27 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_notificationblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.review",
            ),
        ),
    ]
