# Generated by Django 5.2 on 2025-09-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_options_comment_pinned_commentvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
