# Generated by Django 5.2 on 2025-09-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
