# Generated by Django 5.2 on 2025-09-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("like", "👍"),
                    ("love", "❤️"),
                    ("laugh", "😂"),
                    ("wow", "😮"),
                    ("sad", "😢"),
                    ("angry", "😡"),
                ],
                max_length=10,
            ),
        ),
    ]
