# Generated by Django 5.2 on 2025-09-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_reaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="opinion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reaction",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("like", "👍"),
                    ("love", ""),
                    ("funny", "😂"),
                    ("wow", "😮"),
                    ("sad", "😢"),
                    ("angry", "😡"),
                ],
                max_length=10,
            ),
        ),
    ]
