# Generated by Django 5.2 on 2025-09-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_reaction_opinion_reaction_rating_alter_reaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_reaction",
            field=models.BooleanField(default=True),
        ),
    ]
