# Generated by Django 4.2.24 on 2025-09-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
