# Generated by Django 4.2.24 on 2025-09-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_post_is_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="platform",
            field=models.CharField(
                choices=[
                    ("pc", "PC"),
                    ("xbox", "Xbox"),
                    ("nintendo", "Nintendo Switch"),
                    ("mobile", "Celular"),
                    ("ps", "PlayStation"),
                ],
                default="pc",
                max_length=20,
            ),
        ),
    ]
